# -*- coding: utf-8 -*-
"""Copy of cnn_عادية.ipynb--------------هذا في الرسالة

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15B6toVxFHe5qM4vC9pObSP0HnKh95ktI
"""

!pip install opencv-python tensorflow scikit-learn

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

import warnings
warnings.filterwarnings("ignore")

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from tensorflow.keras.optimizers import Adam
# Ignore warnings for clean output
warnings.filterwarnings("ignore")

# --- Mount Drive ---
from google.colab import drive
drive.mount('/content/drive')

# --- 2. Data Loading & Preprocessing ---
dataset_path = "/content/drive/MyDrive/Colab Notebooks/ST1-1/Training"
categories = ["notumor", "pituitary"]
IMG_SIZE = 64

data, labels = [], []

print("🔄 Loading Dataset...")
for idx, category in enumerate(categories):
    folder = os.path.join(dataset_path, category)
    if not os.path.exists(folder):
        print(f"⚠️ Warning: Folder {category} not found!")
        continue
    for file in os.listdir(folder):
        img_path = os.path.join(folder, file)
        img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
        if img is not None:
            img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))
            data.append(img)
            labels.append(idx)

data = np.array(data) / 255.0
labels = np.array(labels)
data = data.reshape(-1, IMG_SIZE, IMG_SIZE, 1)

print(f"✅ Total Images: {len(data)}")

# --- 3. Split Data ---
X_train, X_test, y_train, y_test = train_test_split(
    data, labels, test_size=0.2, random_state=42
)

# --- 4. Build CNN Model ---
model = Sequential([
    Conv2D(32, (3,3), activation='relu', input_shape=(IMG_SIZE, IMG_SIZE, 1)),
    MaxPooling2D(2,2),
    Conv2D(64, (3,3), activation='relu'),
    MaxPooling2D(2,2),
    Conv2D(128, (3,3), activation='relu'),
    MaxPooling2D(2,2),
    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.5),
    Dense(64, activation='relu'),
    Dense(2, activation='softmax')
])

model.compile(optimizer=Adam(),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# --- 5. Training ---
print("\n🚀 Starting Training...")
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=50,
    batch_size=16,
    verbose=1
)

# --- 6. Evaluation & Metrics ---
# Predict classes
y_pred_probs = model.predict(X_test)
y_pred = np.argmax(y_pred_probs, axis=1)

print("\n" + "="*50)
print("📊 CLASSIFICATION REPORT")
print("="*50)
# This provides: Precision, Recall, F1-Score, Support, and Weighted Average
print(classification_report(y_test, y_pred, target_names=categories))

loss, acc = model.evaluate(X_test, y_test, verbose=0)
print(f" Overall Accuracy: {acc:.4f}")
print("="*50)

# --- 7. Visualizations ---

# A. Loss Curve
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
plt.plot(history.history['loss'], label='Training Loss', color='#E74C3C', lw=2)
plt.plot(history.history['val_loss'], label='Validation Loss', color='#F39C12', lw=2)
plt.title('Loss Curve')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.grid(alpha=0.3)

# B. Accuracy Curve
plt.subplot(1, 2, 2)
plt.plot(history.history['accuracy'], label='Training Accuracy', color='#2E86C1', lw=2)
plt.plot(history.history['val_accuracy'], label='Validation Accuracy', color='#28B463', lw=2)
plt.title('Accuracy Curve')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()
plt.grid(alpha=0.3)
plt.show()

# C. Confusion Matrix
plt.figure(figsize=(8, 6))
cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=categories, yticklabels=categories)
plt.title('Confusion Matrix')
plt.xlabel('Predicted label')
plt.ylabel('True label')
plt.show()